[versions]
# Android SDK
android-sdk-min = "24"
android-sdk-compile = "34"
# Libraries
androidx-annotation = "1.7.0"
androidx-compose-compiler = "1.5.3"
androidx-compose-runtime = "1.5.2"
androidx-datastore = "1.1.0-alpha05"
androidx-espresso-core = "3.5.1"
androidx-junit = "1.1.5"
androidx-material3 = "1.2.0-alpha08"
androidx-navigation-compose = "2.7.3"
kotlinx-coroutines-android = "1.7.3"
medzik-libcrypto = "1.1.0"
# Plugins
android-application = "8.1.1"
jetbrains-kotlin-android = "1.9.10"

[libraries]
androidx-annotation = { group = "androidx.annotation", name = "annotation", version.ref = "androidx-annotation" }
androidx-compose-compiler = { group = "androidx.compose.compiler", name = "compiler", version.ref = "androidx-compose-compiler" }
androidx-compose-runtime = { module = "androidx.compose.runtime:runtime", version.ref = "androidx-compose-runtime" }
androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "androidx-datastore" }
androidx-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "androidx-espresso-core" }
androidx-junit = { module = "androidx.test.ext:junit", version.ref = "androidx-junit" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "androidx-material3" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "androidx-navigation-compose" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinx-coroutines-android" }
medzik-libcrypto = { module = "dev.medzik:libcrypto", version.ref = "medzik-libcrypto" }

[plugins]
android-application = { id = "com.android.application", version.ref = "android-application" }
android-library = { id = "com.android.library", version.ref = "android-application" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "jetbrains-kotlin-android" }
